[project]
name = "ucartopdoer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "fastapi>=0.116.1",
    "make>=0.1.6.post2",
    "uvicorn>=0.35.0",
]
